sudo: required 

services:
  - docker

before_install:
  - docker build -t mohamedmahrous995/docker-react -f Dockerfile.dev .

script:
  - docker run mohamedmahrous995/docker-react npm run test -- --coverage