sudo: required
language: ruby
services:
  - docker

before_install:
  - sudo apt-get update
  - docker build -t mohamedmahrous995/docker-react -f Dockerfile.dev .

script:
  - docker run mohamedmahrous995/docker-react npm run test -- --coverage